name: Trigger auto deployment for albumfrontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/albumfrontend-AutoDeployTrigger-82695357-2d76-48fc-a9a0-249eebd6fca1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caa38b6d8f7bacr.azurecr.io
          username: ${{ secrets.ALBUMFRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.ALBUMFRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caa38b6d8f7bacr.azurecr.io/albumfrontend:${{ github.sha }}
          file: src/Dockerfile
          context: src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMFRONTEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n albumfrontend -g apwAppForum_ACA --server caa38b6d8f7bacr.azurecr.io --username  ${{ secrets.ALBUMFRONTEND_REGISTRY_USERNAME }} --password ${{ secrets.ALBUMFRONTEND_REGISTRY_PASSWORD }}
            az containerapp update -n albumfrontend -g apwAppForum_ACA --image caa38b6d8f7bacr.azurecr.io/albumfrontend:${{ github.sha }}
